class ErrorCode:
    NOT_FOUND = "RESOURCE_NOT_FOUND"
    ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_ERROR = "INTERNAL_SERVER_ERROR"
    DB_ERROR = "DATABASE_ERROR"
