"""Add inventory models

Revision ID: 05edbc1c8e12
Revises: 9e595535a88c
Create Date: 2026-07-02 12:37:25.409891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05edbc1c8e12'
down_revision: Union[str, None] = '9e595535a88c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inv_warehouses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inv_store_inventory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('productId', sa.String(length=50), nullable=True),
    sa.Column('warehouseId', sa.String(length=36), nullable=True),
    sa.Column('currentStock', sa.Integer(), nullable=True),
    sa.Column('reorderLevel', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('costPrice', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['productId'], ['store_products.id'], ),
    sa.ForeignKeyConstraint(['warehouseId'], ['inv_warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inv_store_inventory_barcode'), 'inv_store_inventory', ['barcode'], unique=True)
    op.create_table('inv_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inventoryId', sa.String(length=36), nullable=True),
    sa.Column('batchNumber', sa.String(length=50), nullable=True),
    sa.Column('expiryDate', sa.DateTime(), nullable=True),
    sa.Column('currentStock', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inventoryId'], ['inv_store_inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inv_batches_batchNumber'), 'inv_batches', ['batchNumber'], unique=False)
    op.create_table('inv_stock_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inventoryId', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('referenceId', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inventoryId'], ['inv_store_inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inv_stock_transactions')
    op.drop_index(op.f('ix_inv_batches_batchNumber'), table_name='inv_batches')
    op.drop_table('inv_batches')
    op.drop_index(op.f('ix_inv_store_inventory_barcode'), table_name='inv_store_inventory')
    op.drop_table('inv_store_inventory')
    op.drop_table('inv_warehouses')
    # ### end Alembic commands ###
