"""add ai and mobile models

Revision ID: 0912bba548e8
Revises: 4fa3b87f3ceb
Create Date: 2026-07-02 14:13:30.054491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0912bba548e8'
down_revision: Union[str, None] = '4fa3b87f3ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
