"""Add InvoiceItem and GSTIN

Revision ID: 09dbe286626b
Revises: 7fec4d2d4ed7
Create Date: 2026-07-02 13:01:15.242034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09dbe286626b'
down_revision: Union[str, None] = '7fec4d2d4ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_invoice_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoiceId', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('hsnCode', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('unitPrice', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('taxRate', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('taxAmount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('totalAmount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['invoiceId'], ['finance_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('finance_invoices', sa.Column('customerGstin', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finance_invoices', 'customerGstin')
    op.drop_table('finance_invoice_items')
    # ### end Alembic commands ###
