"""Add finance features

Revision ID: 2e84308060b9
Revises: 0912bba548e8
Create Date: 2026-07-03 11:16:04.615503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2e84308060b9'
down_revision: Union[str, None] = '0912bba548e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('finance_expenses', sa.Column('receiptUrl', sa.String(length=500), nullable=True))
    op.add_column('finance_expenses', sa.Column('budgetId', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'finance_expenses', 'finance_budgets', ['budgetId'], ['id'])
    op.add_column('finance_invoices', sa.Column('customerId', sa.String(length=36), nullable=True))
    op.add_column('finance_invoices', sa.Column('lrNumber', sa.String(length=100), nullable=True))
    op.add_column('finance_invoices', sa.Column('vehicleNumber', sa.String(length=100), nullable=True))
    op.add_column('finance_invoices', sa.Column('tripReference', sa.String(length=100), nullable=True))
    op.add_column('finance_invoices', sa.Column('amountPaid', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('finance_invoices', sa.Column('isRecurring', sa.Boolean(), nullable=True))
    op.add_column('finance_invoices', sa.Column('recurrenceInterval', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'finance_invoices', 'finance_customers', ['customerId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'finance_invoices', type_='foreignkey')
    op.drop_column('finance_invoices', 'recurrenceInterval')
    op.drop_column('finance_invoices', 'isRecurring')
    op.drop_column('finance_invoices', 'amountPaid')
    op.drop_column('finance_invoices', 'tripReference')
    op.drop_column('finance_invoices', 'vehicleNumber')
    op.drop_column('finance_invoices', 'lrNumber')
    op.drop_column('finance_invoices', 'customerId')
    op.drop_constraint(None, 'finance_expenses', type_='foreignkey')
    op.drop_column('finance_expenses', 'budgetId')
    op.drop_column('finance_expenses', 'receiptUrl')
    op.create_table('security_dummy',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automation_dummy',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mobile_app_config',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('featureName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('featureName'), 'mobile_app_config', ['featureName'], unique=True)
    op.create_table('ai_messages',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('conversationId', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['conversationId'], ['ai_conversations.id'], name=op.f('ai_messages_ibfk_1')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_conversations',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('userId', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_userId'), 'ai_conversations', ['userId'], unique=False)
    # ### end Alembic commands ###
