"""Add Procurement models

Revision ID: 310c3c69b103
Revises: d15988ef3ec8
Create Date: 2026-06-25 12:24:07.702956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310c3c69b103'
down_revision: Union[str, None] = 'd15988ef3ec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('contactEmail', sa.String(length=255), nullable=True),
    sa.Column('contactPhone', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_suppliers_name'), 'procurement_suppliers', ['name'], unique=False)
    op.create_table('procurement_purchase_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('poNumber', sa.String(length=100), nullable=True),
    sa.Column('supplierId', sa.String(length=36), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('totalAmount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('budgetDeducted', sa.Boolean(), nullable=True),
    sa.Column('budgetId', sa.String(length=36), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplierId'], ['procurement_suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procurement_purchase_orders_poNumber'), 'procurement_purchase_orders', ['poNumber'], unique=True)
    op.create_table('procurement_po_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('purchaseOrderId', sa.String(length=36), nullable=True),
    sa.Column('itemName', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unitPrice', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('receivedQuantity', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['purchaseOrderId'], ['procurement_purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('procurement_dummy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_dummy',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('procurement_po_items')
    op.drop_index(op.f('ix_procurement_purchase_orders_poNumber'), table_name='procurement_purchase_orders')
    op.drop_table('procurement_purchase_orders')
    op.drop_index(op.f('ix_procurement_suppliers_name'), table_name='procurement_suppliers')
    op.drop_table('procurement_suppliers')
    # ### end Alembic commands ###
