"""Add Automation and Security models

Revision ID: 4fa3b87f3ceb
Revises: ea8514fc171e
Create Date: 2026-07-02 13:52:05.597903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4fa3b87f3ceb'
down_revision: Union[str, None] = 'ea8514fc171e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_bots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('botId', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('lastRun', sa.DateTime(), nullable=True),
    sa.Column('runsToday', sa.Integer(), nullable=True),
    sa.Column('successRate', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_bots_botId'), 'auto_bots', ['botId'], unique=True)
    op.create_table('inv_warehouses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sec_access_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.String(length=100), nullable=True),
    sa.Column('ipAddress', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sec_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assignedTo', sa.String(length=100), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sec_compliance_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('standard', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('nextAuditDate', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sec_user_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.String(length=100), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_bot_run_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('botId', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('logOutput', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['botId'], ['auto_bots.botId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_invoice_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoiceId', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('hsnCode', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('unitPrice', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('taxRate', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('taxAmount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('totalAmount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['invoiceId'], ['finance_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inv_store_inventory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('productId', sa.String(length=50), nullable=True),
    sa.Column('warehouseId', sa.String(length=36), nullable=True),
    sa.Column('currentStock', sa.Integer(), nullable=True),
    sa.Column('reorderLevel', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('costPrice', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['productId'], ['store_products.id'], ),
    sa.ForeignKeyConstraint(['warehouseId'], ['inv_warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inv_store_inventory_barcode'), 'inv_store_inventory', ['barcode'], unique=True)
    op.create_table('sc_drivers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('licenseNumber', sa.String(length=50), nullable=True),
    sa.Column('licenseExpiryDate', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('assignedVehicleId', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignedVehicleId'], ['sc_fleet_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sc_drivers_licenseNumber'), 'sc_drivers', ['licenseNumber'], unique=True)
    op.create_table('inv_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inventoryId', sa.String(length=36), nullable=True),
    sa.Column('batchNumber', sa.String(length=50), nullable=True),
    sa.Column('expiryDate', sa.DateTime(), nullable=True),
    sa.Column('currentStock', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inventoryId'], ['inv_store_inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inv_batches_batchNumber'), 'inv_batches', ['batchNumber'], unique=False)
    op.create_table('inv_stock_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inventoryId', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('referenceId', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inventoryId'], ['inv_store_inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sc_driver_duty_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driverId', sa.String(length=36), nullable=True),
    sa.Column('startTime', sa.DateTime(), nullable=True),
    sa.Column('endTime', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driverId'], ['sc_drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sc_trips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicleId', sa.String(length=36), nullable=True),
    sa.Column('driverId', sa.String(length=36), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('destination', sa.String(length=100), nullable=True),
    sa.Column('plannedRoute', sa.Text(), nullable=True),
    sa.Column('startTime', sa.DateTime(), nullable=True),
    sa.Column('endTime', sa.DateTime(), nullable=True),
    sa.Column('distance', sa.String(length=50), nullable=True),
    sa.Column('fuelCost', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driverId'], ['sc_drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicleId'], ['sc_fleet_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_eway_bills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ewayBillNumber', sa.String(length=50), nullable=True),
    sa.Column('shipmentId', sa.String(length=36), nullable=True),
    sa.Column('invoiceId', sa.String(length=36), nullable=True),
    sa.Column('vehicleNumber', sa.String(length=50), nullable=True),
    sa.Column('fromGstin', sa.String(length=50), nullable=True),
    sa.Column('toGstin', sa.String(length=50), nullable=True),
    sa.Column('fromAddress', sa.Text(), nullable=True),
    sa.Column('toAddress', sa.Text(), nullable=True),
    sa.Column('goodsValue', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('hsnCode', sa.String(length=50), nullable=True),
    sa.Column('distanceKm', sa.Integer(), nullable=True),
    sa.Column('validUntil', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoiceId'], ['finance_invoices.id'], ),
    sa.ForeignKeyConstraint(['shipmentId'], ['sc_shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_eway_bills_ewayBillNumber'), 'compliance_eway_bills', ['ewayBillNumber'], unique=True)
    op.create_table('sc_lorry_receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lrNumber', sa.String(length=50), nullable=True),
    sa.Column('consignor', sa.String(length=255), nullable=True),
    sa.Column('consignee', sa.String(length=255), nullable=True),
    sa.Column('goodsDescription', sa.Text(), nullable=True),
    sa.Column('weight', sa.String(length=50), nullable=True),
    sa.Column('freightTerms', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('tripId', sa.String(length=36), nullable=True),
    sa.Column('shipmentId', sa.String(length=36), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipmentId'], ['sc_shipments.id'], ),
    sa.ForeignKeyConstraint(['tripId'], ['sc_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sc_lorry_receipts_lrNumber'), 'sc_lorry_receipts', ['lrNumber'], unique=True)
    op.drop_table('security_dummy')
    op.drop_table('automation_dummy')
    op.add_column('finance_invoices', sa.Column('customerGstin', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_finance_invoices_customerName'), 'finance_invoices', ['customerName'], unique=False)
    op.add_column('sc_shipments', sa.Column('tripId', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'sc_shipments', 'sc_trips', ['tripId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sc_shipments', type_='foreignkey')
    op.drop_column('sc_shipments', 'tripId')
    op.drop_index(op.f('ix_finance_invoices_customerName'), table_name='finance_invoices')
    op.drop_column('finance_invoices', 'customerGstin')
    op.create_table('automation_dummy',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_dummy',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_sc_lorry_receipts_lrNumber'), table_name='sc_lorry_receipts')
    op.drop_table('sc_lorry_receipts')
    op.drop_index(op.f('ix_compliance_eway_bills_ewayBillNumber'), table_name='compliance_eway_bills')
    op.drop_table('compliance_eway_bills')
    op.drop_table('sc_trips')
    op.drop_table('sc_driver_duty_logs')
    op.drop_table('inv_stock_transactions')
    op.drop_index(op.f('ix_inv_batches_batchNumber'), table_name='inv_batches')
    op.drop_table('inv_batches')
    op.drop_index(op.f('ix_sc_drivers_licenseNumber'), table_name='sc_drivers')
    op.drop_table('sc_drivers')
    op.drop_index(op.f('ix_inv_store_inventory_barcode'), table_name='inv_store_inventory')
    op.drop_table('inv_store_inventory')
    op.drop_table('finance_invoice_items')
    op.drop_table('auto_bot_run_logs')
    op.drop_table('sec_user_activities')
    op.drop_table('sec_compliance_items')
    op.drop_table('sec_alerts')
    op.drop_table('sec_access_logs')
    op.drop_table('inv_warehouses')
    op.drop_index(op.f('ix_auto_bots_botId'), table_name='auto_bots')
    op.drop_table('auto_bots')
    # ### end Alembic commands ###
