"""Add Supply Chain models

Revision ID: 7f5cb6d19629
Revises: 9969ae3c34a8
Create Date: 2026-06-25 12:38:51.080481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f5cb6d19629'
down_revision: Union[str, None] = '9969ae3c34a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sc_fleet_vehicles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('registrationNumber', sa.String(length=50), nullable=True),
    sa.Column('vehicleType', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('currentLocation', sa.String(length=100), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sc_fleet_vehicles_registrationNumber'), 'sc_fleet_vehicles', ['registrationNumber'], unique=True)
    op.create_table('sc_shipments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trackingNumber', sa.String(length=100), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('destination', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('eta', sa.DateTime(), nullable=True),
    sa.Column('podSignature', sa.Text(), nullable=True),
    sa.Column('vehicleId', sa.String(length=36), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicleId'], ['sc_fleet_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sc_shipments_trackingNumber'), 'sc_shipments', ['trackingNumber'], unique=True)
    op.create_table('sc_vehicle_locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicleId', sa.String(length=36), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicleId'], ['sc_fleet_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sc_vehicle_maintenance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicleId', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('cost', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('scheduledDate', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicleId'], ['sc_fleet_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sc_customs_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shipmentId', sa.String(length=36), nullable=True),
    sa.Column('documentType', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipmentId'], ['sc_shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('supply_chain_dummy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supply_chain_dummy',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sc_customs_documents')
    op.drop_table('sc_vehicle_maintenance')
    op.drop_table('sc_vehicle_locations')
    op.drop_index(op.f('ix_sc_shipments_trackingNumber'), table_name='sc_shipments')
    op.drop_table('sc_shipments')
    op.drop_index(op.f('ix_sc_fleet_vehicles_registrationNumber'), table_name='sc_fleet_vehicles')
    op.drop_table('sc_fleet_vehicles')
    # ### end Alembic commands ###
