"""Add LorryReceipt model

Revision ID: 7fec4d2d4ed7
Revises: 05edbc1c8e12
Create Date: 2026-07-02 12:50:26.316327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fec4d2d4ed7'
down_revision: Union[str, None] = '05edbc1c8e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sc_lorry_receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lrNumber', sa.String(length=50), nullable=True),
    sa.Column('consignor', sa.String(length=255), nullable=True),
    sa.Column('consignee', sa.String(length=255), nullable=True),
    sa.Column('goodsDescription', sa.Text(), nullable=True),
    sa.Column('weight', sa.String(length=50), nullable=True),
    sa.Column('freightTerms', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('tripId', sa.String(length=36), nullable=True),
    sa.Column('shipmentId', sa.String(length=36), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipmentId'], ['sc_shipments.id'], ),
    sa.ForeignKeyConstraint(['tripId'], ['sc_trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sc_lorry_receipts_lrNumber'), 'sc_lorry_receipts', ['lrNumber'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sc_lorry_receipts_lrNumber'), table_name='sc_lorry_receipts')
    op.drop_table('sc_lorry_receipts')
    # ### end Alembic commands ###
