"""Add Banking models

Revision ID: 9703a5813b3d
Revises: 7f5cb6d19629
Create Date: 2026-06-25 12:44:47.973689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9703a5813b3d'
down_revision: Union[str, None] = '7f5cb6d19629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banking_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('accountName', sa.String(length=100), nullable=True),
    sa.Column('accountNumber', sa.String(length=50), nullable=True),
    sa.Column('bankName', sa.String(length=100), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banking_accounts_accountNumber'), 'banking_accounts', ['accountNumber'], unique=True)
    op.create_table('banking_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('accountId', sa.String(length=36), nullable=True),
    sa.Column('transactionDate', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('reconciled', sa.Boolean(), nullable=True),
    sa.Column('matchedInvoiceId', sa.String(length=36), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accountId'], ['banking_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('banking_dummy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banking_dummy',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('banking_transactions')
    op.drop_index(op.f('ix_banking_accounts_accountNumber'), table_name='banking_accounts')
    op.drop_table('banking_accounts')
    # ### end Alembic commands ###
