"""Add driver and trip models

Revision ID: 9e595535a88c
Revises: 9703a5813b3d
Create Date: 2026-07-02 12:26:42.832184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e595535a88c'
down_revision: Union[str, None] = '9703a5813b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sc_drivers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('licenseNumber', sa.String(length=50), nullable=True),
    sa.Column('licenseExpiryDate', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('assignedVehicleId', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignedVehicleId'], ['sc_fleet_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sc_drivers_licenseNumber'), 'sc_drivers', ['licenseNumber'], unique=True)
    op.create_table('sc_driver_duty_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('driverId', sa.String(length=36), nullable=True),
    sa.Column('startTime', sa.DateTime(), nullable=True),
    sa.Column('endTime', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driverId'], ['sc_drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sc_trips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vehicleId', sa.String(length=36), nullable=True),
    sa.Column('driverId', sa.String(length=36), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('destination', sa.String(length=100), nullable=True),
    sa.Column('plannedRoute', sa.Text(), nullable=True),
    sa.Column('startTime', sa.DateTime(), nullable=True),
    sa.Column('endTime', sa.DateTime(), nullable=True),
    sa.Column('distance', sa.String(length=50), nullable=True),
    sa.Column('fuelCost', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driverId'], ['sc_drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicleId'], ['sc_fleet_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sc_shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tripId', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'sc_trips', ['tripId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sc_shipments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tripId')
    op.drop_table('sc_trips')
    op.drop_table('sc_driver_duty_logs')
    op.drop_index(op.f('ix_sc_drivers_licenseNumber'), table_name='sc_drivers')
    op.drop_table('sc_drivers')
    # ### end Alembic commands ###
