"""Add finance currency and audit logs

Revision ID: c3692bd6b486
Revises: 
Create Date: 2026-06-25 11:59:04.142336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3692bd6b486'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_dummy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets_dummy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ipAddress', sa.String(length=50), nullable=True),
    sa.Column('userAgent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automation_dummy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banking_dummy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_dummy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('erp_departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('finance_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('balance', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_accounts_code'), 'finance_accounts', ['code'], unique=True)
    op.create_index(op.f('ix_finance_accounts_name'), 'finance_accounts', ['name'], unique=False)
    op.create_table('finance_approval_workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requestNo', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('requester', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('currentLevel', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_approval_workflows_requestNo'), 'finance_approval_workflows', ['requestNo'], unique=True)
    op.create_table('finance_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('tableName', sa.String(length=100), nullable=True),
    sa.Column('recordId', sa.String(length=36), nullable=True),
    sa.Column('oldValue', sa.Text(), nullable=True),
    sa.Column('newValue', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_budgets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('budgetName', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('costCenter', sa.String(length=100), nullable=True),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('spent', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_expenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('paidBy', sa.String(length=255), nullable=True),
    sa.Column('receiptStatus', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('approvedBy', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoiceNo', sa.String(length=100), nullable=True),
    sa.Column('customerName', sa.String(length=255), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('taxRate', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('taxAmount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('totalAmount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('invoiceDate', sa.String(length=50), nullable=True),
    sa.Column('dueDate', sa.DateTime(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_invoices_invoiceNo'), 'finance_invoices', ['invoiceNo'], unique=True)
    op.create_table('finance_journal_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('blockIndex', sa.Integer(), nullable=True),
    sa.Column('voucherType', sa.String(length=50), nullable=True),
    sa.Column('voucherNo', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('debitAcc', sa.String(length=100), nullable=True),
    sa.Column('creditAcc', sa.String(length=100), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('prevHash', sa.String(length=255), nullable=True),
    sa.Column('blockHash', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_journal_entries_blockIndex'), 'finance_journal_entries', ['blockIndex'], unique=False)
    op.create_index(op.f('ix_finance_journal_entries_voucherNo'), 'finance_journal_entries', ['voucherNo'], unique=True)
    op.create_table('finance_statements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('statementType', sa.String(length=100), nullable=True),
    sa.Column('period', sa.String(length=100), nullable=True),
    sa.Column('totalIncome', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('totalExpense', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('netAmount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_tax_deadlines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('taxName', sa.String(length=255), nullable=True),
    sa.Column('taxType', sa.String(length=100), nullable=True),
    sa.Column('rate', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('applicableOn', sa.String(length=255), nullable=True),
    sa.Column('effectiveDate', sa.DateTime(), nullable=True),
    sa.Column('dueDate', sa.DateTime(), nullable=True),
    sa.Column('period', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_employees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employeeId', sa.String(length=50), nullable=True),
    sa.Column('fullName', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('departmentId', sa.String(length=36), nullable=True),
    sa.Column('departmentName', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('employeeType', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('dateOfJoining', sa.Date(), nullable=True),
    sa.Column('dateOfBirth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('managerId', sa.String(length=36), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('avatarUrl', sa.String(length=500), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_employees_email'), 'hr_employees', ['email'], unique=True)
    op.create_index(op.f('ix_hr_employees_employeeId'), 'hr_employees', ['employeeId'], unique=True)
    op.create_index(op.f('ix_hr_employees_fullName'), 'hr_employees', ['fullName'], unique=False)
    op.create_table('hr_job_postings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('departmentId', sa.String(length=36), nullable=True),
    sa.Column('departmentName', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('jobType', sa.String(length=50), nullable=True),
    sa.Column('experienceLevel', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('salaryMin', sa.Float(), nullable=True),
    sa.Column('salaryMax', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('openings', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_leave_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('totalDays', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_shifts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('startTime', sa.String(length=20), nullable=True),
    sa.Column('endTime', sa.String(length=20), nullable=True),
    sa.Column('hoursPerDay', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketing_dummy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_dummy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procurement_dummy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects_dummy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_dummy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supply_chain_dummy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_dummy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('erp_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('departmentId', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['departmentId'], ['erp_departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_approval_levels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflowId', sa.String(length=36), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('approver', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.String(length=100), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflowId'], ['finance_approval_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_attendance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employeeId', sa.String(length=36), nullable=True),
    sa.Column('employeeName', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('checkIn', sa.String(length=20), nullable=True),
    sa.Column('checkOut', sa.String(length=20), nullable=True),
    sa.Column('hoursWorked', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employeeId'], ['hr_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_attendance_date'), 'hr_attendance', ['date'], unique=False)
    op.create_table('hr_job_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('jobPostingId', sa.String(length=36), nullable=True),
    sa.Column('applicantName', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('resumeUrl', sa.String(length=500), nullable=True),
    sa.Column('coverLetter', sa.Text(), nullable=True),
    sa.Column('currentStage', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jobPostingId'], ['hr_job_postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_leave_balances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employeeId', sa.String(length=36), nullable=True),
    sa.Column('leaveTypeId', sa.String(length=36), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('entitled', sa.Integer(), nullable=True),
    sa.Column('used', sa.Integer(), nullable=True),
    sa.Column('remaining', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employeeId'], ['hr_employees.id'], ),
    sa.ForeignKeyConstraint(['leaveTypeId'], ['hr_leave_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_leave_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employeeId', sa.String(length=36), nullable=True),
    sa.Column('employeeName', sa.String(length=255), nullable=True),
    sa.Column('leaveTypeId', sa.String(length=36), nullable=True),
    sa.Column('leaveTypeName', sa.String(length=100), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.Column('totalDays', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reviewedBy', sa.String(length=255), nullable=True),
    sa.Column('reviewedAt', sa.DateTime(), nullable=True),
    sa.Column('reviewNote', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employeeId'], ['hr_employees.id'], ),
    sa.ForeignKeyConstraint(['leaveTypeId'], ['hr_leave_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_onboarding_checklists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employeeId', sa.String(length=36), nullable=True),
    sa.Column('totalTasks', sa.Integer(), nullable=True),
    sa.Column('completedTasks', sa.Integer(), nullable=True),
    sa.Column('progressPercent', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('targetDate', sa.Date(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employeeId'], ['hr_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_onboarding_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employeeId', sa.String(length=36), nullable=True),
    sa.Column('employeeName', sa.String(length=255), nullable=True),
    sa.Column('taskName', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('assignedTo', sa.String(length=255), nullable=True),
    sa.Column('dueDate', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completedAt', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employeeId'], ['hr_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_performance_goals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employeeId', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('targetDate', sa.Date(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employeeId'], ['hr_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_performance_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employeeId', sa.String(length=36), nullable=True),
    sa.Column('employeeName', sa.String(length=255), nullable=True),
    sa.Column('reviewerId', sa.String(length=36), nullable=True),
    sa.Column('reviewerName', sa.String(length=255), nullable=True),
    sa.Column('reviewPeriod', sa.String(length=100), nullable=True),
    sa.Column('overallRating', sa.Float(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('improvements', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('dueDate', sa.Date(), nullable=True),
    sa.Column('submittedAt', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employeeId'], ['hr_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('erp_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwordHash', sa.String(length=255), nullable=False),
    sa.Column('fullName', sa.String(length=255), nullable=False),
    sa.Column('roleId', sa.String(length=36), nullable=False),
    sa.Column('departmentId', sa.String(length=36), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('isCEO', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['departmentId'], ['erp_departments.id'], ),
    sa.ForeignKeyConstraint(['roleId'], ['erp_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('module_access',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('roleId', sa.String(length=36), nullable=False),
    sa.Column('moduleKey', sa.String(length=100), nullable=False),
    sa.Column('canRead', sa.Boolean(), nullable=True),
    sa.Column('canWrite', sa.Boolean(), nullable=True),
    sa.Column('canExport', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['roleId'], ['erp_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fullName', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reviewedBy', sa.String(length=36), nullable=True),
    sa.Column('reviewedAt', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('denialReason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reviewedBy'], ['erp_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('isRevoked', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['erp_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens')
    op.drop_table('access_requests')
    op.drop_table('module_access')
    op.drop_table('erp_users')
    op.drop_table('hr_performance_reviews')
    op.drop_table('hr_performance_goals')
    op.drop_table('hr_onboarding_tasks')
    op.drop_table('hr_onboarding_checklists')
    op.drop_table('hr_leave_requests')
    op.drop_table('hr_leave_balances')
    op.drop_table('hr_job_applications')
    op.drop_index(op.f('ix_hr_attendance_date'), table_name='hr_attendance')
    op.drop_table('hr_attendance')
    op.drop_table('finance_approval_levels')
    op.drop_table('erp_roles')
    op.drop_table('support_dummy')
    op.drop_table('supply_chain_dummy')
    op.drop_table('security_dummy')
    op.drop_table('projects_dummy')
    op.drop_table('procurement_dummy')
    op.drop_table('payroll_dummy')
    op.drop_table('marketing_dummy')
    op.drop_table('hr_shifts')
    op.drop_table('hr_leave_types')
    op.drop_table('hr_job_postings')
    op.drop_index(op.f('ix_hr_employees_fullName'), table_name='hr_employees')
    op.drop_index(op.f('ix_hr_employees_employeeId'), table_name='hr_employees')
    op.drop_index(op.f('ix_hr_employees_email'), table_name='hr_employees')
    op.drop_table('hr_employees')
    op.drop_table('finance_tax_deadlines')
    op.drop_table('finance_statements')
    op.drop_index(op.f('ix_finance_journal_entries_voucherNo'), table_name='finance_journal_entries')
    op.drop_index(op.f('ix_finance_journal_entries_blockIndex'), table_name='finance_journal_entries')
    op.drop_table('finance_journal_entries')
    op.drop_index(op.f('ix_finance_invoices_invoiceNo'), table_name='finance_invoices')
    op.drop_table('finance_invoices')
    op.drop_table('finance_expenses')
    op.drop_table('finance_budgets')
    op.drop_table('finance_audit_logs')
    op.drop_index(op.f('ix_finance_approval_workflows_requestNo'), table_name='finance_approval_workflows')
    op.drop_table('finance_approval_workflows')
    op.drop_index(op.f('ix_finance_accounts_name'), table_name='finance_accounts')
    op.drop_index(op.f('ix_finance_accounts_code'), table_name='finance_accounts')
    op.drop_table('finance_accounts')
    op.drop_table('erp_departments')
    op.drop_table('crm_dummy')
    op.drop_table('banking_dummy')
    op.drop_table('automation_dummy')
    op.drop_table('audit_logs')
    op.drop_table('assets_dummy')
    op.drop_table('analytics_dummy')
    # ### end Alembic commands ###
