"""Add Payroll models

Revision ID: d15988ef3ec8
Revises: feeb214a0f02
Create Date: 2026-06-25 12:12:28.284312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15988ef3ec8'
down_revision: Union[str, None] = 'feeb214a0f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_tax_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('minSalary', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('maxSalary', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('taxPercent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employeeId', sa.String(length=36), nullable=True),
    sa.Column('employeeName', sa.String(length=255), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('baseSalary', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('allowances', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('unpaidLeaveDeductionDays', sa.Integer(), nullable=True),
    sa.Column('unpaidLeaveDeductionAmount', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('taxDeduction', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('netPay', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payslipPdf', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('processedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employeeId'], ['hr_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('payroll_dummy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_dummy',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('payroll_records')
    op.drop_table('payroll_tax_rules')
    # ### end Alembic commands ###
