"""Add EwayBill

Revision ID: ea8514fc171e
Revises: 09dbe286626b
Create Date: 2026-07-02 13:25:24.463871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea8514fc171e'
down_revision: Union[str, None] = '09dbe286626b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_eway_bills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ewayBillNumber', sa.String(length=50), nullable=True),
    sa.Column('shipmentId', sa.String(length=36), nullable=True),
    sa.Column('invoiceId', sa.String(length=36), nullable=True),
    sa.Column('vehicleNumber', sa.String(length=50), nullable=True),
    sa.Column('fromGstin', sa.String(length=50), nullable=True),
    sa.Column('toGstin', sa.String(length=50), nullable=True),
    sa.Column('fromAddress', sa.Text(), nullable=True),
    sa.Column('toAddress', sa.Text(), nullable=True),
    sa.Column('goodsValue', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('hsnCode', sa.String(length=50), nullable=True),
    sa.Column('distanceKm', sa.Integer(), nullable=True),
    sa.Column('validUntil', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoiceId'], ['finance_invoices.id'], ),
    sa.ForeignKeyConstraint(['shipmentId'], ['sc_shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_eway_bills_ewayBillNumber'), 'compliance_eway_bills', ['ewayBillNumber'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_eway_bills_ewayBillNumber'), table_name='compliance_eway_bills')
    op.drop_table('compliance_eway_bills')
    # ### end Alembic commands ###
