"""Add HRDocuments and unpaidLeaveDeductionDays

Revision ID: feeb214a0f02
Revises: c3692bd6b486
Create Date: 2026-06-25 12:04:05.973607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feeb214a0f02'
down_revision: Union[str, None] = 'c3692bd6b486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employeeId', sa.String(length=36), nullable=True),
    sa.Column('documentName', sa.String(length=255), nullable=True),
    sa.Column('documentType', sa.String(length=100), nullable=True),
    sa.Column('fileData', sa.Text(), nullable=True),
    sa.Column('uploadedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employeeId'], ['hr_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hr_employees', sa.Column('unpaidLeaveDeductionDays', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_employees', 'unpaidLeaveDeductionDays')
    op.drop_table('hr_documents')
    # ### end Alembic commands ###
